// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241205064003_OptimizeBackend")]
    partial class OptimizeBackend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "Type");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 28,
                            Type = "movie",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 12,
                            Type = "movie",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 16,
                            Type = "movie",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 35,
                            Type = "movie",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 80,
                            Type = "movie",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 99,
                            Type = "movie",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 18,
                            Type = "movie",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 10751,
                            Type = "movie",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 14,
                            Type = "movie",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 36,
                            Type = "movie",
                            Name = "History"
                        },
                        new
                        {
                            Id = 27,
                            Type = "movie",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10402,
                            Type = "movie",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 9648,
                            Type = "movie",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 10749,
                            Type = "movie",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 878,
                            Type = "movie",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 10770,
                            Type = "movie",
                            Name = "TV Movie"
                        },
                        new
                        {
                            Id = 53,
                            Type = "movie",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10752,
                            Type = "movie",
                            Name = "War"
                        },
                        new
                        {
                            Id = 37,
                            Type = "movie",
                            Name = "Western"
                        },
                        new
                        {
                            Id = 10759,
                            Type = "tv",
                            Name = "Action & Adventure"
                        },
                        new
                        {
                            Id = 16,
                            Type = "tv",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 35,
                            Type = "tv",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 80,
                            Type = "tv",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 99,
                            Type = "tv",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 18,
                            Type = "tv",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 10751,
                            Type = "tv",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 10762,
                            Type = "tv",
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 9648,
                            Type = "tv",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 10763,
                            Type = "tv",
                            Name = "News"
                        },
                        new
                        {
                            Id = 10764,
                            Type = "tv",
                            Name = "Reality"
                        },
                        new
                        {
                            Id = 10765,
                            Type = "tv",
                            Name = "Sci-Fi & Fantasy"
                        },
                        new
                        {
                            Id = 10766,
                            Type = "tv",
                            Name = "Soap"
                        },
                        new
                        {
                            Id = 10767,
                            Type = "tv",
                            Name = "Talk"
                        },
                        new
                        {
                            Id = 10768,
                            Type = "tv",
                            Name = "War & Politics"
                        },
                        new
                        {
                            Id = 37,
                            Type = "tv",
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("backend.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GenreIds")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("backend.Models.TVShow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FirstAirDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreIds")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TVShows");
                });
#pragma warning restore 612, 618
        }
    }
}
